# clamd configuration for CSC Zanzibar dev stack
LogFile /tmp/clamd.log
LogFileMaxSize 2M
LogTime yes
LogClean yes
LogVerbose yes
TCPSocket 3310
TCPAddr 0.0.0.0
MaxThreads 12
ReadTimeout 180
CommandReadTimeout 30
StreamMaxLength 25M